apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: my-aks-cluster
  namespace: crossplane-system
spec:
  resourceRef:
    apiVersion: containerservice.azure.crossplane.io/v1alpha3
    kind: AKSCluster
    name: aks-cluster
  classRef:
    apiVersion: containerservice.azure.crossplane.io/v1alpha3
    kind: AKSClusterClass
    name: aks-cluster-class
  writeConnectionSecretToRef:
    name: my-aks-cluster-connection
